### PR TITLE
index.html dependant

### PR DESCRIPTION
**Pull request by atom-dispencer**
Now dependant on index.html files. I have tested all of the links and resources and they work to my knowledge on a local scale. Any problems please contact me.

### CODE REVIEW

**Review by Minion3665 — APPROVED** [review]
Looks good 👍

**Review by Minion3665 — CHANGES_REQUESTED** [review]
Nevermind, you didn't sign the commit so it's useless

**Comment by atom-dispencer** [comment]
Ik this isn't good :((((((((
I thought it did sign rip

**Comment by atom-dispencer** [comment]
@Minion3665 can I resign the commits?

**Review by atom-dispencer — COMMENTED** [review]
Please hellpppppppp can I sign these? I've reviewed them????

**Pull request closed without merging**
